# Generated by Django 5.0.3 on 2024-03-25 11:57

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snsapp', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=markdownx.models.MarkdownxField(help_text='Markdown形式で書いてください。', verbose_name='本文'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=markdownx.models.MarkdownxField(help_text='Markdown形式で書いてください。', verbose_name='本文'),
        ),
    ]
